// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYU293toDU7d1WoahZ1hQUaT-25-mzuyk',
    appId: '1:335977392113:web:a3a12e9245b8cca6c1c650',
    messagingSenderId: '335977392113',
    projectId: 'mychat-f4b77',
    authDomain: 'mychat-f4b77.firebaseapp.com',
    storageBucket: 'mychat-f4b77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwMalAU0eJQfnB4SA4V5lBsNyTxEx3kc4',
    appId: '1:335977392113:android:b8d1cf7ff3e1193ec1c650',
    messagingSenderId: '335977392113',
    projectId: 'mychat-f4b77',
    storageBucket: 'mychat-f4b77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_qkBGXm_Y6BdQeEXioMEMUYRjUn-GBX0',
    appId: '1:335977392113:ios:ce0fc6006dd0e433c1c650',
    messagingSenderId: '335977392113',
    projectId: 'mychat-f4b77',
    storageBucket: 'mychat-f4b77.appspot.com',
    iosBundleId: 'com.example.nansu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_qkBGXm_Y6BdQeEXioMEMUYRjUn-GBX0',
    appId: '1:335977392113:ios:751ba18d3c12c9c9c1c650',
    messagingSenderId: '335977392113',
    projectId: 'mychat-f4b77',
    storageBucket: 'mychat-f4b77.appspot.com',
    iosBundleId: 'com.example.nansu.RunnerTests',
  );
}
